#Exercicio: Faça um programa que leia algo pelom teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.#
var = input("Digite algo: ")
print("O tipo primitivo desse valor é:", type(var))
print("É alfabético?", var.isalpha())
print("É numérico?", var.isnumeric())
print("É alfanumérico?", var.isalnum())
print("Está em maiúsculas?", var.isupper())
print("Está em minúsculas?", var.islower())
print("Está capitalizada?", var.istitle())
print("É um espaço em branco?", var.isspace())
print("É um dígito?", var.isdigit())
print("É um identificador válido?", var.isidentifier())
print("É um número decimal?", var.isdecimal())
print("É um número real?", var.isnumeric())
print("É um número inteiro?", var.isdigit())
print("É um número de ponto flutuante?", var.replace('.', '', 1).isdigit() and var.count('.') < 2)
print("É um número complexo?", var.replace('j', '', 1).replace('.', '', 1).isdigit() and var.count('j') < 2 and var.count('.') < 2)
print("É um número binário?", all(c in '01' for c in var))
print("É um número octal?", all(c in '01234567' for c in var))
print("É um número hexadecimal?", all(c in '0123456789abcdefABCDEF' for c in var))
print("É um número romano?", all(c in 'IVXLCDM' for c in var.upper()))
print("É um número em notação científica?", 'e' in var.lower() and var.replace('e', '', 1).replace('.', '', 1).isdigit() and var.count('e') < 2 and var.count('.') < 2)
